apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
      annotations:
        # Correctly disabling Dynatrace CSI/webhook injection for Agentless OTLP
        oneagent.dynatrace.com/inject: "false"
    spec:
      containers:
      - image: vedranregistry99.azurecr.io/worker
        name: worker
        
        env:
        - name: DT_ENDPOINT_URL
          valueFrom:
            secretKeyRef:
              name: dynatrace-otlp-secret 
              key: endpoint_url          
        - name: DT_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: dynatrace-otlp-secret
              key: api_token
        
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
      imagePullSecrets:
      - name: acr-secret