# worker-deployment.yaml snippet
spec:
  template:
    # ...
    spec:
      containers:
      - image: vedranregistry99.azurecr.io/worker
        name: worker
        
        env:
        - name: DT_ENDPOINT_URL
          valueFrom:
            secretKeyRef:
              # Must match the name you found: dynatrace-otel-secrets
              name: dynatrace-otel-secrets 
              key: endpoint_url 
              
        - name: DT_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              # Must match the name you found: dynatrace-otel-secrets
              name: dynatrace-otel-secrets
              key: api_token
      